server:
  port: 8080

gateway:
  account-lock:
    timeout-ms: 3000
  aeron:
    enabled: true
    channel: aeron:ipc
    stream-id: 2001
    account-lock-request-stream-id: 2101
    account-lock-response-stream-id: 2102
  random-order:
    enabled: true
    fixed-delay-ms: 1000
